name: PHP Composer

on:
  push:
    branches: [main, build-matrix]
  pull_request:
    branches: [main]
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        #@wontfix 'windows-latest', 'macos-latest'
        operating-system: ['ubuntu-latest']
        #@wontfix v.5.3 conflicts with php-cs-fixer
        #@todo fix v.8 conflicts with phpunit
        php-versions: ['5.6', '7.1', '7.4'] 
        #phpunit-versions: ['latest']

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, curl
          ini-values: post_max_size=256M, max_execution_time=180
          #coverage: xdebug        
          #tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      # - name: Cache Composer packages
      #   id: composer-cache
      #   uses: actions/cache@v2
      #   with:
      #     path: vendor
      #     key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md
      - name: Composer Autoload
        run: composer dump-autoload

      - name: Run test suite
        run: composer run-script test
